name: Build and Push Multiarch Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multiarch image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: cristianestmaida/gestion-productos:v2
          platforms: linux/amd64,linux/arm64
